### ISSUE TITLE
create UI design

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#18] opened 2024-05-11 02:36 UTC
create UI design for the project using any of the available tools like figma, adobe XD, in Vision, etc.

**Comment by kart2004** [comment] 2024-05-11 05:40
Hello, I am Karthik. I have experience working with figma and UI in general, could you please assign this to me as a part of GSSOC'24? @samarthhapse

**Comment by codershrutik** [comment] 2024-05-11 07:06
@samarthhapse I have experience working in the UIUX domain, and have designed, as well as coded the websites of multiple start-ups such as Ozibook, BerryWiki. Can you please assign this issue to me as part of GSSOC'24?

**Comment by poojaverma9578** [comment] 2024-05-11 07:15
As a contributor for GSSOC 24, I am excited to leverage my skills and contribute to this project by designing the UI. My expertise includes proficiency in figma, adobe XD, and user-centric design principles.

**Comment by TomLucasakaTGeek** [comment] 2024-05-11 16:36
Hello @samarthhapse I have worked on various frontend projects like **Chat Application**, **Payment-Portal**, etc. assign this issue to me under _gssoc'24_ and get it solved within _**2 hours**_.

**Comment by hetvipopat** [comment] 2024-05-12 04:02
Hello @samarthhapse, I'm interested in working on this issue (GSSOC'24)

**Comment by Rajneeshkarya** [comment] 2024-05-12 05:46
Hi @samarthhapse , As a contributor I would like to do this task for you. Could you please assign this task to me under GSSOC'24?

**Comment by Suruchibharti** [comment] 2024-05-12 12:35
hey,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by samarthhapse** [comment] 2024-05-12 12:52
@TomLucasakaTGeek I just want the figma design of my complete website. Will you be okay to do by yourself or I can assign this task to one more contributor .So you both can c-o/rdinte and make it happen within 2 days.

**Comment by TomLucasakaTGeek** [comment] 2024-05-12 16:26
Hey @samarthhapse, thank you for considering me I can do this alone but if the designs are complex I am open to work in collaboration too.

**Comment by samarthhapse** [comment] 2024-05-13 12:26
Tonight I will provide you with the basic sketch for UI here => [TanmayEmpowers@proton.me](mailto:TanmayEmpowers@proton.me) 
Try to complete till 15th EOD ,
If you find it complex , comment below I will ask one more contributor to collaborate , okay ?

**Comment by TomLucasakaTGeek** [comment] 2024-05-13 13:50
Hello @samarthhapse actually I have my exams till 15th, and I can work dedicated from the evening of 15th, I can try and start working but may not guarantee that the designs will be ready by 15th EOD, maybe extend the deadline to 16th or 17th.

**Comment by samarthhapse** [comment] 2024-05-14 17:06
okay @TomLucasakaTGeek  but get it ready by 18th Morning.

**Comment by TomLucasakaTGeek** [comment] 2024-05-14 17:12
Thank you sir please send the designs over mail.

**Comment by samarthhapse** [comment] 2024-05-26 17:03
Hello everyone there , #70  if you are experienced in advanced react and tailwind and willing to work on same signup and login page to update the old simple one in to the super cool page with attention seeking animations and much more changes in UI only

**Comment by samarthhapse** [comment] 2024-06-03 16:43
Hello everyone there https://github.com/samarthhapse/sarthi/issues/90 if you are experienced in advanced react and tailwind and willing to work on creating a cool profile page

**Comment by Gokilp** [comment] 2024-06-06 05:58
Can asssign to me I working on issue

**Closed** 2024-07-02 05:31 UTC
Labels: good first issue, gssoc
