### ISSUE TITLE
Added sign in with google and sign up with google in both student and expert page

### ISSUE THREAD

**Issue by Krishna100604** [samarthhapse/sarthi#191] opened 2024-06-22 09:40 UTC
![Screenshot (123)](https://github.com/samarthhapse/sarthi/assets/110299021/c7cfff02-b0ad-4e35-8d66-b596b43a0c14)
![Screenshot (122)](https://github.com/samarthhapse/sarthi/assets/110299021/5b32c554-4742-4b64-8ebe-ad4e23e98f4f)
![Screenshot (125)](https://github.com/samarthhapse/sarthi/assets/110299021/8bfb006d-6861-4b7c-8e78-857fe827e0df)
![Screenshot (124)](https://github.com/samarthhapse/sarthi/assets/110299021/29755c69-2c5a-45e8-a719-0ba189c2fa95)

@samarthhapse assign me this issue

**Comment by Krishna100604** [comment] 2024-06-22 09:41
assign me this under vsoc'24

**Comment by ROKUMATE** [comment] 2024-06-22 17:20
@Krishna100604 Its the same Issue Of #128 
and its added in the code base ig

**Comment by Krishna100604** [comment] 2024-06-22 17:35
> @Krishna100604 Its the same Issue Of #128 and its added in the code base ig

no i just forked it today it's not added

**Comment by ROKUMATE** [comment] 2024-06-22 18:37
its ib temp4 branch updated one ig

**Comment by Krishna100604** [comment] 2024-06-23 02:04
> its updated on temp branch not temp4 one ig

okk

**Comment by samarthhapse** [comment] 2024-06-23 12:53
@ROKUMATE , can you work on building the frontend for chat functionality. Backend code is already available. Pls comment below if you can create only frontend according to it. I will open new issue for you and assign it with level 3 to you only

**Comment by samarthhapse** [comment] 2024-06-23 14:35
@ROKUMATE pls see above shared images by Krishna. This was what I was expecting you to do. Nut you have changed the UI completely and I think some part of backend also. You were actually expected to only add one button for signin with google(not changing the the UI of complete UI)

**Comment by Krishna100604** [comment] 2024-06-23 15:04
> @ROKUMATE pls see above shared images by Krishna. This was what I was expecting you to do. Nut you have changed the UI completely and I think some part of backend also. You were actually expected to only add one button for signin with google(not changing the the UI of complete pages of student and expert)

can you assign it to me

**Comment by samarthhapse** [comment] 2024-06-23 15:12
Hello Krishna firstly let @ROKUMATE comment here , then I will surely assign tp you

**Comment by Krishna100604** [comment] 2024-06-23 15:12
> Hello Krishna firstly let @ROKUMATE comment here , then I will surely assign tp you

okk

**Comment by samarthhapse** [comment] 2024-06-23 15:13
@ROKUMATE he deserves the acceptance for this one. Because he actually worked on this for 2 days. But got into this confusion

**Comment by samarthhapse** [comment] 2024-06-23 15:13
@Krishna100604 pls wait !

**Comment by Krishna100604** [comment] 2024-06-23 15:13
> @ROKUMATE he deserves the acceptance for this one. Because he actually worked on this for 2 days. But got into this confusion

hmm ohk

**Comment by samarthhapse** [comment] 2024-06-24 04:00
@Krishna100604 , pls start working on this

**Comment by samarthhapse** [comment] 2024-06-24 04:02
@Krishna100604 for adding labels , from which program you are contributor gssoc'24 OR vsoc'24

**Comment by Krishna100604** [comment] 2024-06-24 04:17
> @Krishna100604 for adding labels , from which program you are contributor gssoc'24 OR vsoc'24

vsoc'24

**Comment by samarthhapse** [comment] 2024-06-24 04:21
okay @Krishna100604 added labels , pls fork latest code from temp branch and raise PR asap

**Comment by Krishna100604** [comment] 2024-06-24 04:51
@samarthhapse i created PR

**Comment by Krishna100604** [comment] 2024-06-24 04:52
BTW how many points will i get

**Comment by samarthhapse** [comment] 2024-06-24 05:12
Are you able to signin/up with google properly

**Comment by Krishna100604** [comment] 2024-06-24 05:24
> @Krishna100604 Are you able to signin/up with google properly as student and expert as well

you need to create a client key for that like API key for authentication it is just a UI i made

**Comment by samarthhapse** [comment] 2024-06-24 05:27
> > @Krishna100604 Are you able to signin/up with google properly as student and expert as well
> 
> you need to create a client key for that like API key for authentication it is just a UI i made

That's the main thing Krishna. You are expected to implement completely

**Comment by Krishna100604** [comment] 2024-06-24 06:18
okk i will try

**Comment by samarthhapse** [comment] 2024-06-24 06:20
@Krishna100604 Can you surely complete it surely by today

**Comment by Krishna100604** [comment] 2024-06-24 06:51
no by tomm i can finish

**Comment by Krishna100604** [comment] 2024-06-24 06:54
but i think for backend you have to create an api and client key for google auth since it is your project so i can not crate my api key

**Comment by samarthhapse** [comment] 2024-06-24 10:11
you can create of your own for you to use

**Comment by samarthhapse** [comment] 2024-06-24 17:58
@Krishna100604 are you ready to complete it

**Comment by Krishna100604** [comment] 2024-06-25 02:40
okk i try

**Comment by samarthhapse** [comment] 2024-06-25 02:43
@Krishna100604 , If you try and take 2 days. And if task is not completed then it may waste time of the project

**Comment by samarthhapse** [comment] 2024-06-25 02:44
@Krishna100604 can I assign it to Rohit

**Comment by Krishna100604** [comment] 2024-06-25 03:27
yeah if he can do it you can assign him maybe i work on another feature

**Comment by samarthhapse** [comment] 2024-06-25 03:36
okay

**Comment by samarthhapse** [comment] 2024-06-25 03:37
@ROKUMATE can you complete this issue as per frontend of Krishna and your backend

**Comment by samarthhapse** [comment] 2024-06-25 03:39
@ROKUMATE once pls , go through Krishna's PR. If I merge his PR , can you add your code. OR you want to make it completely of your own

**Comment by ROKUMATE** [comment] 2024-06-25 10:07
@samarthhapse Sir i have already created the functionality using the Appwrite package ... 
that is what my pull request was ... 

what u want mee to do exactly in the code now can you specify ?

**Comment by samarthhapse** [comment] 2024-06-25 18:53
@ROKUMATE  you have to copy paste same code for current temp branch without changing ui of current signin/up pages. Just add buttons like krishna's shared images

**Comment by ROKUMATE** [comment] 2024-06-25 19:19
Ohk sir i will do it 👍

**Comment by ROKUMATE** [comment] 2024-06-25 19:37
so sir you gonna merge his pull request then i have to work naa as of now the ui is not updated yet in the codebase

**Comment by samarthhapse** [comment] 2024-06-27 02:37
@ROKUMATE , merged the PR of Krishna. Pls start working.

**Comment by samarthhapse** [comment] 2024-06-27 02:38
@ROKUMATE  Pls try to complete by today. I also have some more issues for you as you are experienced in MERN

**Comment by samarthhapse** [comment] 2024-06-27 02:56
@ROKUMATE added you as assignee and level3 label too. Pls hurry !

**Comment by ROKUMATE** [comment] 2024-06-27 18:31
@samarthhapse If u want any changes in that do tell, 

else the issue is completed now

**Comment by samarthhapse** [comment] 2024-06-28 15:22
@ROKUMATE I will merge you PR within two days. Cany you wok on integrating chat box functionality for the app in MERN stack completely

**Comment by Krishna100604** [comment] 2024-06-28 17:00
@samarthhapse you didn't give me points for last PR

**Closed** 2024-07-05 03:17 UTC
Labels: gssoc, level3, VSoC’24, BONUS
